name: ev
description: " "
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.2.0
  cupertino_icons: ^1.0.6
  web_socket_channel: ^2.1.0 # Add this line to it.
  http: ^0.13.3  # Replace with the latest version of the http package
  crypto: ^3.0.3
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_speed_dial: ^5.0.0


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Image/